/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.0.0-rc
 */

export interface Nomenclature {
  id: string
  label: string
  [key: string]: unknown
}
