/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.0.0-rc
 */
import type { Nomenclature } from './nomenclature'

/**
 * Validation of nomenclatures for an interrogation
 */
export type SchemaNomenclature = Nomenclature[]
