packages:
  - '.'

minimumReleaseAge: 0

allowBuilds:
  '@parcel/watcher': true
  esbuild: true

patchedDependencies:
  '@storybook/addon-interactions@8.6.14': patches/@storybook__addon-interactions@8.6.14.patch
  '@storybook/addon-toolbars@8.6.14': patches/@storybook__addon-toolbars@8.6.14.patch
  '@storybook/blocks@8.6.14': patches/@storybook__blocks@8.6.14.patch
