/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.5.0
 */
import type { SchemaVariableType } from '../schema.variable-type/schemaVariableType'

export interface CollectedValues {
  COLLECTED?: SchemaVariableType
  EDITED?: SchemaVariableType
  FORCED?: SchemaVariableType
  INPUTED?: SchemaVariableType
  INPUTTED?: SchemaVariableType
  PREVIOUS?: SchemaVariableType
}
