/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.5.0
 */

export * from './_'
export * from './collectedValues'
export * from './schemaCollectedData'
