/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.6.1
 */
import type { CampaignSummarySensitivity } from './campaignSummarySensitivity'

export interface CampaignSummary {
  id?: string
  sensitivity?: CampaignSummarySensitivity
  questionnaireIds?: string[]
}
