/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.5.0
 */

export type CampaignCreationV2Sensitivity =
  (typeof CampaignCreationV2Sensitivity)[keyof typeof CampaignCreationV2Sensitivity]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CampaignCreationV2Sensitivity = {
  NORMAL: 'NORMAL',
  SENSITIVE: 'SENSITIVE',
} as const
