/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.6.1
 */

export type CampaignSummarySensitivity =
  (typeof CampaignSummarySensitivity)[keyof typeof CampaignSummarySensitivity]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CampaignSummarySensitivity = {
  NORMAL: 'NORMAL',
  SENSITIVE: 'SENSITIVE',
} as const
