/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.5.0
 */

export type CampaignSensitivity =
  (typeof CampaignSensitivity)[keyof typeof CampaignSensitivity]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CampaignSensitivity = {
  NORMAL: 'NORMAL',
  SENSITIVE: 'SENSITIVE',
} as const
