/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.6.1
 */
import type { CampaignMetadata } from './campaignMetadata'
import type { CampaignSensitivity } from './campaignSensitivity'

export interface Campaign {
  id?: string
  sensitivity?: CampaignSensitivity
  questionnaireIds?: string[]
  metadata?: CampaignMetadata
}
