/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.6.1
 */

export type EventPayloadLeafStatesInnerDtoState =
  (typeof EventPayloadLeafStatesInnerDtoState)[keyof typeof EventPayloadLeafStatesInnerDtoState]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventPayloadLeafStatesInnerDtoState = {
  INIT: 'INIT',
  COMPLETED: 'COMPLETED',
} as const
