/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.6.1
 */
import type { EventPayloadDtoMode } from './eventPayloadDtoMode'
import type { EventPayloadLeafStatesInnerDto } from './eventPayloadLeafStatesInnerDto'

export interface EventPayloadDto {
  interrogationId: string
  mode: EventPayloadDtoMode
  leafStates?: EventPayloadLeafStatesInnerDto[]
}
