/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.6.1
 */
import type { EventDtoAggregateType } from './eventDtoAggregateType'
import type { EventDtoEventType } from './eventDtoEventType'
import type { EventPayloadDto } from './eventPayloadDto'

export interface EventDto {
  correlationId?: string
  eventType: EventDtoEventType
  aggregateType: EventDtoAggregateType
  payload: EventPayloadDto
}
