/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.6.1
 */

export type GetInterrogationsByStateDataStateData =
  (typeof GetInterrogationsByStateDataStateData)[keyof typeof GetInterrogationsByStateDataStateData]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetInterrogationsByStateDataStateData = {
  INIT: 'INIT',
  COMPLETED: 'COMPLETED',
  VALIDATED: 'VALIDATED',
  TOEXTRACT: 'TOEXTRACT',
  EXTRACTED: 'EXTRACTED',
  IS_MOVED: 'IS_MOVED',
} as const
