/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.0.0-rc
 */

export type GetInterrogationsByStateState =
  (typeof GetInterrogationsByStateState)[keyof typeof GetInterrogationsByStateState]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetInterrogationsByStateState = {
  INIT: 'INIT',
  COMPLETED: 'COMPLETED',
  VALIDATED: 'VALIDATED',
  TOEXTRACT: 'TOEXTRACT',
  EXTRACTED: 'EXTRACTED',
} as const
