/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.0.0-rc
 */
import type { GetInterrogationsByStateState } from './getInterrogationsByStateState'

export type GetInterrogationsByStateParams = {
  state: GetInterrogationsByStateState
}
