/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.5.0
 */
import type { SchemaCollectedData } from './schema.collected-data/schemaCollectedData'
import type { StateDataUpdate } from './stateDataUpdate'

export interface InterrogationDataStateDataUpdate {
  data?: SchemaCollectedData
  stateData: StateDataUpdate
}
