/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.5.0
 */
import type { InterrogationUpdateComment } from './interrogationUpdateComment'
import type { SchemaData } from './schema.data/schemaData'
import type { SchemaPersonalization } from './schema.personalization/schemaPersonalization'
import type { StateDataForInterrogationUpdate } from './stateDataForInterrogationUpdate'

export interface InterrogationUpdate {
  personalization?: SchemaPersonalization
  data?: SchemaData
  comment?: InterrogationUpdateComment
  stateData?: StateDataForInterrogationUpdate
}
