/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.0.0-rc
 */
import type { InterrogationCreationComment } from './interrogationCreationComment'
import type { SchemaData } from './schema.data/schemaData'
import type { SchemaPersonalization } from './schema.personalization/schemaPersonalization'
import type { StateDataUpdate } from './stateDataUpdate'

export interface InterrogationCreation {
  id?: string
  surveyUnitId?: string
  questionnaireId: string
  personalization: SchemaPersonalization
  data: SchemaData
  comment: InterrogationCreationComment
  stateData?: StateDataUpdate
}
