/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.6.1
 */

export type InterrogationMetadataContext =
  (typeof InterrogationMetadataContext)[keyof typeof InterrogationMetadataContext]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InterrogationMetadataContext = {
  household: 'household',
  business: 'business',
} as const
