/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.5.0
 */

export type IntegrationResultUnitStatus =
  (typeof IntegrationResultUnitStatus)[keyof typeof IntegrationResultUnitStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IntegrationResultUnitStatus = {
  CREATED: 'CREATED',
  UPDATED: 'UPDATED',
  ERROR: 'ERROR',
} as const
