/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.6.1
 */
import type { InterrogationComment } from './interrogationComment'
import type { SchemaData } from './schema.data/schemaData'
import type { SchemaPersonalization } from './schema.personalization/schemaPersonalization'
import type { StateData } from './stateData'

export interface Interrogation {
  id?: string
  questionnaireId?: string
  personalization?: SchemaPersonalization
  data?: SchemaData
  comment?: InterrogationComment
  stateData?: StateData
  locked?: boolean
}
