/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.5.0
 */
import type { IntegrationResultUnitStatus } from './integrationResultUnitStatus'

export interface IntegrationResultUnit {
  id?: string
  status?: IntegrationResultUnitStatus
  cause?: string
}
