/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.6.1
 */
import type { SchemaData } from './schema.data/schemaData'
import type { SchemaPersonalization } from './schema.personalization/schemaPersonalization'

export interface InterrogationCreation {
  id?: string
  surveyUnitId?: string
  questionnaireId: string
  personalization?: SchemaPersonalization
  data: SchemaData
}
