/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Events API
 * API for managing various event types in the system
 * OpenAPI spec version: 1.0.0
 */
import type { LeafStatesUpdatedEventPayload } from './leafStatesUpdatedEventPayload'
import type { LeafStatesUpdatedEventType } from './leafStatesUpdatedEventType'

export interface LeafStatesUpdatedEvent {
  type: LeafStatesUpdatedEventType
  payload: LeafStatesUpdatedEventPayload
}
