/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Events API
 * API for managing various event types in the system
 * OpenAPI spec version: 1.0.0
 */
import type { LeafState } from './leafState'

export type LeafStatesUpdatedEventPayload = {
  /** Unique identifier for the interrogation */
  interrogationId: string
  /** Array of leaf state objects */
  leafStates: LeafState[]
}
