/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Events API
 * API for managing various event types in the system
 * OpenAPI spec version: 1.0.0
 */

export type LeafStatesUpdatedEventType =
  (typeof LeafStatesUpdatedEventType)[keyof typeof LeafStatesUpdatedEventType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LeafStatesUpdatedEventType = {
  LEAF_STATES_UPDATED: 'LEAF_STATES_UPDATED',
} as const
