/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Events API
 * API for managing various event types in the system
 * OpenAPI spec version: 1.0.0
 */

/**
 * The state value, can be null or a specific state like COMPLETED
 * @nullable
 */
export type LeafStateState =
  | (typeof LeafStateState)[keyof typeof LeafStateState]
  | null

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LeafStateState = {
  COMPLETED: 'COMPLETED',
  INIT: 'INIT',
} as const
