/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Events API
 * API for managing various event types in the system
 * OpenAPI spec version: 1.0.0
 */
import type { LeafStateState } from './leafStateState'

export interface LeafState {
  /**
   * The state value, can be null or a specific state like COMPLETED
   * @nullable
   */
  state: LeafStateState
  /** Date and time of the state (ISO 8601 format) */
  date: number
}
