/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Events API
 * API for managing various event types in the system
 * OpenAPI spec version: 1.0.0
 */

export type MultimodeMovedEventType =
  (typeof MultimodeMovedEventType)[keyof typeof MultimodeMovedEventType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MultimodeMovedEventType = {
  MULTIMODE_MOVED: 'MULTIMODE_MOVED',
  MULTIMODE_SPLIT: 'MULTIMODE_SPLIT',
} as const
