/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Events API
 * API for managing various event types in the system
 * OpenAPI spec version: 1.0.0
 */
import type { LeafStatesUpdatedEvent } from './leafStatesUpdatedEvent'
import type { MultimodeMovedEvent } from './multimodeMovedEvent'
import type { QuestionnaireEvent } from './questionnaireEvent'

export type PostEventsBody =
  | MultimodeMovedEvent
  | QuestionnaireEvent
  | LeafStatesUpdatedEvent
