/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Events API
 * API for managing various event types in the system
 * OpenAPI spec version: 1.0.0
 */

export type QuestionnaireEventType =
  (typeof QuestionnaireEventType)[keyof typeof QuestionnaireEventType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QuestionnaireEventType = {
  QUESTIONNAIRE_INIT: 'QUESTIONNAIRE_INIT',
  QUESTIONNAIRE_VALIDATED: 'QUESTIONNAIRE_VALIDATED',
  QUESTIONNAIRE_COMPLETED: 'QUESTIONNAIRE_COMPLETED',
  QUESTIONNAIRE_UPDATED: 'QUESTIONNAIRE_UPDATED',
} as const
