/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.6.1
 */
import type { QuestionnaireModelCreationValue } from './questionnaireModelCreationValue'

export interface QuestionnaireModelCreation {
  idQuestionnaireModel?: string
  /** @minLength 1 */
  label: string
  value: QuestionnaireModelCreationValue
  requiredNomenclatureIds?: string[]
}
