/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Events API
 * API for managing various event types in the system
 * OpenAPI spec version: 1.0.0
 */
import type { QuestionnaireEventPayload } from './questionnaireEventPayload'
import type { QuestionnaireEventType } from './questionnaireEventType'

export interface QuestionnaireEvent {
  type: QuestionnaireEventType
  payload: QuestionnaireEventPayload
}
