/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.6.1
 */
import type { QuestionnaireModelValueValue } from './questionnaireModelValueValue'

export interface QuestionnaireModelValue {
  value?: QuestionnaireModelValueValue
}
