/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.6.1
 */
import type { StateDataUpdateState } from './stateDataUpdateState'

export interface StateDataUpdate {
  state: StateDataUpdateState
  /** @minLength 1 */
  currentPage: string
}
