/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.6.1
 */

export type StateDataForInterrogationUpdateState =
  (typeof StateDataForInterrogationUpdateState)[keyof typeof StateDataForInterrogationUpdateState]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StateDataForInterrogationUpdateState = {
  INIT: 'INIT',
  COMPLETED: 'COMPLETED',
  VALIDATED: 'VALIDATED',
  TOEXTRACT: 'TOEXTRACT',
  EXTRACTED: 'EXTRACTED',
} as const
