/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.0.0-rc
 */
import type { SchemaCollectedData } from '../schema.collected-data/schemaCollectedData'

/**
 * Validation of interrogation data
 */
export interface SchemaData {
  CALCULATED?: unknown
  EXTERNAL?: unknown
  COLLECTED?: SchemaCollectedData
  [key: string]: unknown
}
