/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Events API
 * API for managing various event types in the system
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query'

import type { PostEventsBody } from '../models/api'
import { stromaeInstance } from './axiosInstance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Creates different types of events based on the event type
 * @summary Create an event
 */
export const postEvents = (
  postEventsBody: PostEventsBody,
  options?: SecondParameter<typeof stromaeInstance>,
  signal?: AbortSignal,
) => {
  return stromaeInstance<void>(
    {
      url: `/api/events`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postEventsBody,
      signal,
    },
    options,
  )
}

export const getPostEventsMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postEvents>>,
    TError,
    { data: PostEventsBody },
    TContext
  >
  request?: SecondParameter<typeof stromaeInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof postEvents>>,
  TError,
  { data: PostEventsBody },
  TContext
> => {
  const mutationKey = ['postEvents']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postEvents>>,
    { data: PostEventsBody }
  > = (props) => {
    const { data } = props ?? {}

    return postEvents(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostEventsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postEvents>>
>
export type PostEventsMutationBody = PostEventsBody
export type PostEventsMutationError = void

/**
 * @summary Create an event
 */
export const usePostEvents = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postEvents>>,
      TError,
      { data: PostEventsBody },
      TContext
    >
    request?: SecondParameter<typeof stromaeInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postEvents>>,
  TError,
  { data: PostEventsBody },
  TContext
> => {
  const mutationOptions = getPostEventsMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
