/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.6.1
 */
import { useMutation } from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query'

import type { EventDto } from '../models/api'
import { stromaeInstance } from './axiosInstance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Save an event
 */
export const addEvent = (
  eventDto: EventDto,
  options?: SecondParameter<typeof stromaeInstance>,
  signal?: AbortSignal,
) => {
  return stromaeInstance<void>(
    {
      url: `/api/events`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: eventDto,
      signal,
    },
    options,
  )
}

export const getAddEventMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addEvent>>,
    TError,
    { data: EventDto },
    TContext
  >
  request?: SecondParameter<typeof stromaeInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof addEvent>>,
  TError,
  { data: EventDto },
  TContext
> => {
  const mutationKey = ['addEvent']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addEvent>>,
    { data: EventDto }
  > = (props) => {
    const { data } = props ?? {}

    return addEvent(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AddEventMutationResult = NonNullable<
  Awaited<ReturnType<typeof addEvent>>
>
export type AddEventMutationBody = EventDto
export type AddEventMutationError = unknown

/**
 * @summary Save an event
 */
export const useAddEvent = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addEvent>>,
      TError,
      { data: EventDto },
      TContext
    >
    request?: SecondParameter<typeof stromaeInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addEvent>>,
  TError,
  { data: EventDto },
  TContext
> => {
  const mutationOptions = getAddEventMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
