/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.5.0
 */

export type SchemaMetadataInseeContext =
  (typeof SchemaMetadataInseeContext)[keyof typeof SchemaMetadataInseeContext]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SchemaMetadataInseeContext = {
  household: 'household',
  business: 'business',
} as const
