/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * queen-api
 * API for Queen/Stromae
 * OpenAPI spec version: 5.6.1
 */
import type { SchemaMetadataInseeContext } from './schemaMetadataInseeContext'
import type { Variable } from './variable'

export interface SchemaMetadata {
  inseeContext?: SchemaMetadataInseeContext
  /** @minItems 0 */
  variables?: Variable[]
  [key: string]: unknown
}
